import { Service } from "./types";

export const services: readonly Service[] = [
  {
    id: "mens-haircut",
    name: "Men's Haircut",
    description: "Classic or modern cut tailored to your style",
    price: 25,
    duration: 30,
    category: "barber",
  },
  {
    id: "fade",
    name: "Fade",
    description: "Skin fade, mid fade, or taper fade",
    price: 30,
    duration: 30,
    category: "barber",
  },
  {
    id: "beard-trim",
    name: "Beard Trim",
    description: "Shape and trim for a clean, polished look",
    price: 15,
    duration: 20,
    category: "barber",
  },
  {
    id: "hot-shave",
    name: "Hot Towel Shave",
    description: "Traditional straight razor shave with hot towel",
    price: 35,
    duration: 45,
    category: "barber",
  },
  {
    id: "haircut-beard",
    name: "Haircut + Beard Combo",
    description: "Full haircut with beard trim and lineup",
    price: 40,
    duration: 45,
    category: "barber",
  },
  {
    id: "kids-cut",
    name: "Kids Haircut",
    description: "Haircut for children 12 and under",
    price: 18,
    duration: 20,
    category: "barber",
  },
  {
    id: "womens-cut",
    name: "Women's Haircut",
    description: "Cut and style for any hair length",
    price: 40,
    duration: 45,
    category: "beauty",
  },
  {
    id: "blowout",
    name: "Blowout & Style",
    description: "Wash, blow dry, and style",
    price: 35,
    duration: 45,
    category: "beauty",
  },
  {
    id: "color",
    name: "Hair Coloring",
    description: "Full color, highlights, or balayage",
    price: 80,
    duration: 120,
    category: "beauty",
  },
  {
    id: "manicure",
    name: "Manicure",
    description: "Nail shaping, cuticle care, and polish",
    price: 25,
    duration: 30,
    category: "beauty",
  },
  {
    id: "pedicure",
    name: "Pedicure",
    description: "Relaxing foot soak, nail care, and polish",
    price: 35,
    duration: 45,
    category: "beauty",
  },
  {
    id: "facial",
    name: "Facial Treatment",
    description: "Deep cleansing facial for glowing skin",
    price: 55,
    duration: 60,
    category: "beauty",
  },
  {
    id: "waxing",
    name: "Waxing",
    description: "Eyebrow, lip, or full face waxing",
    price: 15,
    duration: 15,
    category: "beauty",
  },
  {
    id: "gel-nails",
    name: "Gel Nails",
    description: "Long-lasting gel polish application",
    price: 40,
    duration: 45,
    category: "beauty",
  },
];
